name: weixin
on:
  workflow_dispatch:
  schedule: 
    # 代表国际标准时间23点0分，北京时间需要+8小时，代表北京时间上午7点运行
    - cron: '0 23 * * *'
jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
      # 检出代码
      - uses: actions/checkout@v2

      # 设置 Python 环境
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # 使用 3.9.x 的最新版本，避免指定小版本

      # 设置时区为上海
      - name: Set timezone
        run: |
          sudo cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime

      # 安装依赖
      - name: Install pip packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 运行主程序
      # - name: Run weixin script
      #   run: |
      #     python main.py
